// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApzyMa1DKFsOMg9W1sIHZgnaMBjszF_Lo',
    appId: '1:107377147305:web:131e19bca1d129b35e18b8',
    messagingSenderId: '107377147305',
    projectId: 'matchcode-e117d',
    authDomain: 'matchcode-e117d.firebaseapp.com',
    storageBucket: 'matchcode-e117d.appspot.com',
    measurementId: 'G-PQR0V63XM3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV8QAtd8XNT5BxLxw9c5n1GhUWhtvBGi0',
    appId: '1:107377147305:android:15dac8aaaada9e435e18b8',
    messagingSenderId: '107377147305',
    projectId: 'matchcode-e117d',
    storageBucket: 'matchcode-e117d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6g5ng0wd3pamSurzFkNVcyciByMIx2hA',
    appId: '1:107377147305:ios:7e0ad6c85bab44fc5e18b8',
    messagingSenderId: '107377147305',
    projectId: 'matchcode-e117d',
    storageBucket: 'matchcode-e117d.appspot.com',
    androidClientId: '107377147305-asbgvoedhhrtn8ni2jjpk9o3pi4qt4u0.apps.googleusercontent.com',
    iosClientId: '107377147305-mru6ai94eu8tdjgodaaeud10b95psndc.apps.googleusercontent.com',
    iosBundleId: 'com.example.languageMatch',
  );
}
